spring:
  config:
    import: application-secrets.properties

  data:
    mongodb:
      database: journal_DevelopmentDB
      uri: mongodb+srv://${mongodb.username}:${mongodb.password}@${mongodb.url}
      auto-index-creation: ${mongodb.auto-index-creation-bool}